export const envVariablesRequired: String[] = [
    "NODEMAIL_SENDER_NAME",
    "NODEMAIL_SENDER_HOST",
    "NODEMAIL_SENDER_PORT",
    "NODEMAIL_SENDER_SECURE",
    "NODEMAIL_SENDER_USERNAME",
    "NODEMAIL_SENDER_PASSWORD",
    "NODEMAIL_SENDER_SECURE",
    "NODEMAIL_SENDER_TLS_CIPHERS",
]